Message-ID: <5171456078@6218975692>
Date: Tue, 12 Dec 2023 21:55:01 +0700
MIME-Version: 1.0
Content-Language: vi-VN
To: minhhieudo2545@gmail.com
From: minhhieudo2545@gmal.com
Subject: Test
Content-Type: text/rtf; charset=UTF-8

{\rtf1\fbidis\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil Segoe UI;}}
{\colortbl ;\red255\green255\blue255;}
{\*\generator Riched20 3.1.0004}\viewkind4\uc1 
\pard\tx720\cf1\f0\fs21 This is a test \b email\f1\par
}

